---
name: Publish rss2go

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build docker image
              run: docker build -f Containerfile -t rss2go:latest .

            - name: Push docker image
              run: |
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                  docker tag rss2go:latest "${{ secrets.DOCKER_USERNAME }}/rss2go:latest"
                  docker push "${{ secrets.DOCKER_USERNAME }}/rss2go:latest"
...
